<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RivetContractOutputPath>$(MSBuildProjectDirectory)\.rivet\rivet.contract.json</RivetContractOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\core\rivet.core\Rivet.Core.csproj" />
        <ProjectReference Include="..\..\core\rivet.generator\Rivet.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <CompilerVisibleProperty Include="RivetContractOutputPath" />
    </ItemGroup>

</Project>
