using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Rivet.Generator;

/// <summary>
/// 扫描 Rivet 特性并生成语言无关契约文件。
/// </summary>
[Generator]
public sealed class BridgeGenerator : IIncrementalGenerator
{
    /// <summary>
    /// MSBuild 暴露给 Source Generator 的 contract 输出路径属性名。
    /// </summary>
    private const string ContractPathProperty = "build_property.RivetContractOutputPath";

    /// <summary>
    /// [JsBindable] 标记成员不符合第一阶段公开 Rv<T> 属性约定时的编译期诊断。
    /// </summary>
    private static readonly DiagnosticDescriptor InvalidBindableDescriptor = new(
        "RIVET001",
        "Rivet bindable property must be public Rv<T>",
        "Rivet bindable member '{0}/{1}' must be a public Rv<T> property",
        "Rivet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>
    /// [JsCallable] 标记方法不符合第一阶段公开非泛型方法约定时的编译期诊断。
    /// </summary>
    private static readonly DiagnosticDescriptor InvalidCallableDescriptor = new(
        "RIVET002",
        "Rivet callable method must be public and non-generic",
        "Rivet callable method '{0}/{1}' must be public and non-generic",
        "Rivet",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>
    /// 注册增量生成管线，收集 Rivet 契约类型并在构建期间刷新 contract 文件。
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributedTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is MethodDeclarationSyntax or PropertyDeclarationSyntax or VariableDeclaratorSyntax,
                static (syntaxContext, _) => TryGetRivetType(syntaxContext))
            .Where(static type => type is not null)
            .Select(static (type, _) => type!)
            .Collect();

        var options = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) => provider.GlobalOptions);

        context.RegisterSourceOutput(attributedTypes.Combine(options), static (sourceContext, pair) =>
        {
            var (types, globalOptions) = pair;
            ReportContractDiagnostics(sourceContext, types);

            sourceContext.AddSource(
                "Rivet.Contract.Marker.g.cs",
                "// <auto-generated />\nnamespace Rivet.Generated { internal static class RivetContractMarker { } }\n");

            if (!globalOptions.TryGetValue(ContractPathProperty, out var outputPath) || string.IsNullOrWhiteSpace(outputPath))
            {
                return;
            }

            var contract = BuildContract(types);
            WriteIfChanged(outputPath, contract);
        });
    }

    /// <summary>
    /// 从候选语法节点解析包含 Rivet 契约成员的服务类型。
    /// </summary>
    private static INamedTypeSymbol? TryGetRivetType(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node);
        if (symbol is not IMethodSymbol and not IPropertySymbol and not IFieldSymbol)
        {
            return null;
        }

        if (!HasRivetAttribute(symbol) && !IsImplicitBindableProperty(symbol))
        {
            return null;
        }

        return symbol.ContainingType;
    }

    /// <summary>
    /// 判断成员是否显式声明了 Rivet 契约特性。
    /// </summary>
    private static bool HasRivetAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(static attribute =>
        {
            var name = attribute.AttributeClass?.ToDisplayString();
            return name is "Rivet.Core.Attributes.JsCallableAttribute"
                or "Rivet.Core.Attributes.JsBindableAttribute"
                or "Rivet.Core.Attributes.JsEventAttribute";
        });
    }

    /// <summary>
    /// 判断公开 Rv<T> 属性是否应在没有 [JsBindable] 时自动进入契约。
    /// </summary>
    private static bool IsImplicitBindableProperty(ISymbol symbol)
    {
        return symbol is IPropertySymbol { DeclaredAccessibility: Accessibility.Public } property
            && TryGetRvValueType(property.Type) is not null;
    }

    /// <summary>
    /// 把常见的 Rivet 契约误用提前成编译期诊断。
    /// </summary>
    private static void ReportContractDiagnostics(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> rawTypes)
    {
        var types = rawTypes
            .Where(static type => type is not null)
            .GroupBy(static type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Select(static group => group.First())
            .ToArray();

        foreach (var type in types)
        {
            foreach (var property in type.GetMembers().OfType<IPropertySymbol>().Where(static property => GetAttribute(property, "Rivet.Core.Attributes.JsBindableAttribute") is not null))
            {
                if (property.DeclaredAccessibility != Accessibility.Public || TryGetRvValueType(property.Type) is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        InvalidBindableDescriptor,
                        property.Locations.FirstOrDefault(),
                        type.Name,
                        property.Name));
                }
            }

            foreach (var field in type.GetMembers().OfType<IFieldSymbol>().Where(static field => GetAttribute(field, "Rivet.Core.Attributes.JsBindableAttribute") is not null))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidBindableDescriptor,
                    field.Locations.FirstOrDefault(),
                    type.Name,
                    field.Name));
            }

            foreach (var method in type.GetMembers().OfType<IMethodSymbol>().Where(static method => GetAttribute(method, "Rivet.Core.Attributes.JsCallableAttribute") is not null))
            {
                if (method.DeclaredAccessibility != Accessibility.Public || method.IsGenericMethod)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        InvalidCallableDescriptor,
                        method.Locations.FirstOrDefault(),
                        type.Name,
                        method.Name));
                }
            }
        }
    }

    /// <summary>
    /// 根据扫描到的服务类型生成完整 contract JSON 文本。
    /// </summary>
    private static string BuildContract(ImmutableArray<INamedTypeSymbol> rawTypes)
    {
        var types = rawTypes
            .Where(static type => type is not null)
            .GroupBy(static type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Select(static group => group.First())
            .OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("{");
        builder.AppendLine("  \"version\": 1,");
        builder.AppendLine("  \"services\": [");

        for (var typeIndex = 0; typeIndex < types.Length; typeIndex++)
        {
            var type = types[typeIndex];
            var serviceName = ToServiceName(type.Name);
            var variables = GetBindableProperties(type, serviceName).ToArray();
            var methods = GetCallableMethods(type, serviceName).ToArray();

            builder.AppendLine("    {");
            AppendJsonProperty(builder, "clrName", type.Name, 6, true);
            AppendJsonProperty(builder, "name", serviceName, 6, true);
            AppendJsonProperty(builder, "description", GetSummary(type), 6, true);
            builder.AppendLine("      \"variables\": [");
            AppendItems(builder, variables, AppendVariable);
            builder.AppendLine("      ],");
            builder.AppendLine("      \"methods\": [");
            AppendItems(builder, methods, AppendMethod);
            builder.AppendLine("      ]");
            builder.Append("    }");
            builder.AppendLine(typeIndex == types.Length - 1 ? string.Empty : ",");
        }

        builder.AppendLine("  ]");
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// 提取服务上所有公开 Rv<T> 属性，生成前端变量契约。
    /// </summary>
    private static IEnumerable<VariableContract> GetBindableProperties(INamedTypeSymbol type, string serviceName)
    {
        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property => GetAttribute(property, "Rivet.Core.Attributes.JsBindableAttribute") is not null || TryGetRvValueType(property.Type) is not null)
            .Where(static property => property.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .Select(property =>
            {
                var attribute = GetAttribute(property, "Rivet.Core.Attributes.JsBindableAttribute");
                var name = ToMemberName(GetAttributeName(attribute) ?? property.Name);
                var valueType = TryGetRvValueType(property.Type) ?? property.Type;
                return new VariableContract(
                    $"{serviceName}.{name}",
                    name,
                    GetSummary(property),
                    valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    ToTsType(valueType));
            });
    }

    /// <summary>
    /// 提取服务上所有公开 [JsCallable] 方法，生成前端方法契约。
    /// </summary>
    private static IEnumerable<MethodContract> GetCallableMethods(INamedTypeSymbol type, string serviceName)
    {
        return type.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static method => method.MethodKind == MethodKind.Ordinary)
            .Where(static method => GetAttribute(method, "Rivet.Core.Attributes.JsCallableAttribute") is not null)
            .Where(static method => method.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(static method => method.Name, StringComparer.Ordinal)
            .Select(method =>
            {
                var attribute = GetAttribute(method, "Rivet.Core.Attributes.JsCallableAttribute");
                var name = ToMemberName(GetAttributeName(attribute) ?? method.Name);
                var returnType = UnwrapTask(method.ReturnType);
                var parameterDescriptions = GetParameterDescriptions(method);
                return new MethodContract(
                    $"{serviceName}.{name}",
                    name,
                    GetSummary(method),
                    method.Parameters
                        .Select(parameter => new ParameterContract(
                            parameter.Name,
                            parameterDescriptions.TryGetValue(parameter.Name, out var description) ? description : string.Empty,
                            ToTsType(parameter.Type)))
                        .ToArray(),
                    GetReturnsDescription(method),
                    ToTsType(returnType));
            });
    }

    /// <summary>
    /// 从 Rv<T> 类型中解析真实业务值类型；非 Rv 状态返回空。
    /// </summary>
    private static ITypeSymbol? TryGetRvValueType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType || namedType.TypeArguments.Length != 1)
        {
            return null;
        }

        return namedType.OriginalDefinition.ToDisplayString() == "Rivet.Core.Rv<T>"
            ? namedType.TypeArguments[0]
            : null;
    }

    /// <summary>
    /// 把 Task 或 Task<T> 的返回类型还原成前端需要看到的业务返回类型。
    /// </summary>
    private static ITypeSymbol UnwrapTask(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return type;
        }

        if (namedType.ToDisplayString() == "System.Threading.Tasks.Task")
        {
            return namedType.ContainingAssembly.GetTypeByMetadataName("System.Void") ?? type;
        }

        return namedType.OriginalDefinition.ToDisplayString() == "System.Threading.Tasks.Task<TResult>" && namedType.TypeArguments.Length == 1
            ? namedType.TypeArguments[0]
            : type;
    }

    /// <summary>
    /// 按完整元数据名称读取指定特性，避免仅按短名称误匹配。
    /// </summary>
    private static AttributeData? GetAttribute(ISymbol symbol, string metadataName)
    {
        return symbol.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == metadataName);
    }

    /// <summary>
    /// 读取 Rivet 特性上的 Name 命名参数；未指定时交给调用方使用成员原名。
    /// </summary>
    private static string? GetAttributeName(AttributeData? attribute)
    {
        if (attribute is null)
        {
            return null;
        }

        foreach (var argument in attribute.NamedArguments)
        {
            if (argument.Key == "Name" && argument.Value.Value is string name && !string.IsNullOrWhiteSpace(name))
            {
                return name;
            }
        }

        return null;
    }

    /// <summary>
    /// 将常见 C# 类型映射成 TypeScript 类型；暂不支持的复杂类型保守降级为 unknown。
    /// </summary>
    private static string ToTsType(ITypeSymbol type)
    {
        var display = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return display switch
        {
            "string" => "string",
            "bool" => "boolean",
            "byte" => "number",
            "sbyte" => "number",
            "short" => "number",
            "ushort" => "number",
            "int" => "number",
            "uint" => "number",
            "long" => "number",
            "ulong" => "number",
            "float" => "number",
            "double" => "number",
            "decimal" => "number",
            "void" => "void",
            "global::System.String" => "string",
            "global::System.Boolean" => "boolean",
            "global::System.Byte" => "number",
            "global::System.SByte" => "number",
            "global::System.Int16" => "number",
            "global::System.UInt16" => "number",
            "global::System.Int32" => "number",
            "global::System.UInt32" => "number",
            "global::System.Int64" => "number",
            "global::System.UInt64" => "number",
            "global::System.Single" => "number",
            "global::System.Double" => "number",
            "global::System.Decimal" => "number",
            "global::System.Void" => "void",
            "global::System.DateTime" => "string",
            "global::System.DateTimeOffset" => "string",
            _ => "unknown",
        };
    }

    /// <summary>
    /// 从 XML 文档注释读取摘要，作为前端代理成员的 TSDoc 主体。
    /// </summary>
    private static string GetSummary(ISymbol symbol)
    {
        return GetDocumentationElementText(symbol, "summary");
    }

    /// <summary>
    /// 从 XML 文档注释读取返回值说明，用于生成 TSDoc 的 returns 标签。
    /// </summary>
    private static string GetReturnsDescription(ISymbol symbol)
    {
        return GetDocumentationElementText(symbol, "returns");
    }

    /// <summary>
    /// 从 XML 文档注释读取参数说明，按参数名提供给 TypeScript 方法代理。
    /// </summary>
    private static IReadOnlyDictionary<string, string> GetParameterDescriptions(ISymbol symbol)
    {
        var document = TryParseDocumentation(symbol);
        if (document?.Root is null)
        {
            return new Dictionary<string, string>();
        }

        return document
            .Descendants("param")
            .Select(element => new
            {
                Name = element.Attribute("name")?.Value,
                Description = NormalizeDocumentationText(element.Value),
            })
            .Where(parameter => !string.IsNullOrWhiteSpace(parameter.Name))
            .ToDictionary(
                parameter => parameter.Name!,
                parameter => parameter.Description,
                StringComparer.Ordinal);
    }

    /// <summary>
    /// 从 XML 文档注释中读取指定元素文本。
    /// </summary>
    private static string GetDocumentationElementText(ISymbol symbol, string elementName)
    {
        var document = TryParseDocumentation(symbol);
        return NormalizeDocumentationText(document?.Descendants(elementName).LastOrDefault()?.Value ?? string.Empty);
    }

    /// <summary>
    /// 解析 Roslyn 提供的 XML 文档注释；解析失败时忽略注释，避免阻断契约生成。
    /// </summary>
    private static XDocument? TryParseDocumentation(ISymbol symbol)
    {
        var syntaxDocument = TryParseDocumentationFromSyntax(symbol);
        if (syntaxDocument is not null)
        {
            return syntaxDocument;
        }

        return TryParseDocumentationFromSymbol(symbol);
    }

    /// <summary>
    /// 从源码前导文档注释解析 XML，避免 symbol 文档在增量生成上下文中丢失 param 等标签。
    /// </summary>
    private static XDocument? TryParseDocumentationFromSyntax(ISymbol symbol)
    {
        foreach (var reference in symbol.DeclaringSyntaxReferences)
        {
            var syntax = reference.GetSyntax();
            var xml = GetLeadingDocumentationXml(syntax);
            if (string.IsNullOrWhiteSpace(xml))
            {
                continue;
            }

            var document = TryParseXml($"<member>{xml}</member>");
            if (document is not null)
            {
                return document;
            }
        }

        return null;
    }

    /// <summary>
    /// 从 Roslyn symbol 读取标准 XML 文档，作为源码注释解析失败时的兜底。
    /// </summary>
    private static XDocument? TryParseDocumentationFromSymbol(ISymbol symbol)
    {
        var xml = symbol.GetDocumentationCommentXml();
        if (string.IsNullOrWhiteSpace(xml))
        {
            return null;
        }

        return TryParseXml(xml!);
    }

    /// <summary>
    /// 提取语法节点前导的 XML 文档注释正文。
    /// </summary>
    private static string GetLeadingDocumentationXml(SyntaxNode syntax)
    {
        var builder = new StringBuilder();
        foreach (var trivia in syntax.GetLeadingTrivia())
        {
            AppendDocumentationTrivia(builder, trivia.ToFullString());
        }

        return builder.ToString();
    }

    /// <summary>
    /// 将 C# 文档注释标记剥离成可解析的 XML 片段。
    /// </summary>
    private static void AppendDocumentationTrivia(StringBuilder builder, string triviaText)
    {
        var lines = triviaText.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
        foreach (var line in lines)
        {
            var content = line.TrimStart();
            if (content.StartsWith("///", StringComparison.Ordinal))
            {
                builder.AppendLine(content.Substring(3).TrimStart());
                continue;
            }

            if (content.StartsWith("/**", StringComparison.Ordinal))
            {
                builder.AppendLine(content.Substring(3).TrimStart());
                continue;
            }

            if (content.StartsWith("*/", StringComparison.Ordinal))
            {
                continue;
            }

            if (content.StartsWith("*", StringComparison.Ordinal))
            {
                builder.AppendLine(content.Substring(1).TrimStart());
                continue;
            }

            if (content.StartsWith("<", StringComparison.Ordinal))
            {
                builder.AppendLine(content);
            }
        }
    }

    /// <summary>
    /// 安全解析 XML 文档片段；解析失败时返回空值并保留上一份成功契约。
    /// </summary>
    private static XDocument? TryParseXml(string xml)
    {
        try
        {
            return XDocument.Parse(xml);
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// 折叠 XML 文档注释的缩进和空白，生成适合 JSON 与 TSDoc 的单行说明。
    /// </summary>
    private static string NormalizeDocumentationText(string value)
    {
        return string.Join(" ", value.Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries));
    }

    /// <summary>
    /// 追加 JSON 数组项，并负责维护元素之间的逗号。
    /// </summary>
    private static void AppendItems<T>(StringBuilder builder, IReadOnlyList<T> items, Action<StringBuilder, T, bool> append)
    {
        for (var index = 0; index < items.Count; index++)
        {
            append(builder, items[index], index == items.Count - 1);
        }
    }

    /// <summary>
    /// 把单个变量契约写入 contract JSON。
    /// </summary>
    private static void AppendVariable(StringBuilder builder, VariableContract variable, bool isLast)
    {
        builder.AppendLine("        {");
        AppendJsonProperty(builder, "key", variable.Key, 10, true);
        AppendJsonProperty(builder, "name", variable.Name, 10, true);
        AppendJsonProperty(builder, "description", variable.Description, 10, true);
        AppendJsonProperty(builder, "clrType", variable.ClrType, 10, true);
        AppendJsonProperty(builder, "tsType", variable.TsType, 10, false);
        builder.Append("        }");
        builder.AppendLine(isLast ? string.Empty : ",");
    }

    /// <summary>
    /// 把单个方法契约及其参数写入 contract JSON。
    /// </summary>
    private static void AppendMethod(StringBuilder builder, MethodContract method, bool isLast)
    {
        builder.AppendLine("        {");
        AppendJsonProperty(builder, "key", method.Key, 10, true);
        AppendJsonProperty(builder, "name", method.Name, 10, true);
        AppendJsonProperty(builder, "description", method.Description, 10, true);
        AppendJsonProperty(builder, "returnType", method.ReturnType, 10, true);
        AppendJsonProperty(builder, "returnDescription", method.ReturnDescription, 10, true);
        builder.AppendLine("          \"parameters\": [");

        for (var index = 0; index < method.Parameters.Count; index++)
        {
            var parameter = method.Parameters[index];
            builder.AppendLine("            {");
            AppendJsonProperty(builder, "name", parameter.Name, 14, true);
            AppendJsonProperty(builder, "description", parameter.Description, 14, true);
            AppendJsonProperty(builder, "tsType", parameter.TsType, 14, false);
            builder.Append("            }");
            builder.AppendLine(index == method.Parameters.Count - 1 ? string.Empty : ",");
        }

        builder.AppendLine("          ]");
        builder.Append("        }");
        builder.AppendLine(isLast ? string.Empty : ",");
    }

    /// <summary>
    /// 追加一个字符串 JSON 属性，并统一处理缩进、转义和尾随逗号。
    /// </summary>
    private static void AppendJsonProperty(StringBuilder builder, string name, string value, int indent, bool comma)
    {
        builder.Append(' ', indent);
        builder.Append('"');
        builder.Append(EscapeJson(name));
        builder.Append("\": \"");
        builder.Append(EscapeJson(value));
        builder.Append('"');
        if (comma)
        {
            builder.Append(',');
        }

        builder.AppendLine();
    }

    /// <summary>
    /// 将后端服务类型名转换成前端服务命名空间，例如 ToolkitService -> toolkit。
    /// </summary>
    private static string ToServiceName(string typeName)
    {
        var name = typeName.EndsWith("Service", StringComparison.Ordinal)
            ? typeName.Substring(0, typeName.Length - "Service".Length)
            : typeName;

        return ToMemberName(name);
    }

    /// <summary>
    /// 将 C# 成员名转换成前端小驼峰成员名。
    /// </summary>
    private static string ToMemberName(string name)
    {
        if (string.IsNullOrEmpty(name) || char.IsLower(name[0]))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    /// <summary>
    /// 转义 contract JSON 字符串中会破坏语法的字符。
    /// </summary>
    private static string EscapeJson(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
    }

    /// <summary>
    /// 内容变化时写入 contract 文件；写入失败时保留上一份成功输出。
    /// </summary>
    private static void WriteIfChanged(string outputPath, string content)
    {
        try
        {
            var directory = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                Directory.CreateDirectory(directory);
            }

            if (File.Exists(outputPath) && File.ReadAllText(outputPath) == content)
            {
                return;
            }

            var tempPath = $"{outputPath}.tmp";
            File.WriteAllText(tempPath, content, Encoding.UTF8);

            if (File.Exists(outputPath))
            {
                File.Delete(outputPath);
            }

            File.Move(tempPath, outputPath);
        }
        catch
        {
            // 生成失败时保留上一份成功 contract，具体编译诊断后续补充。
        }
    }

    /// <summary>
    /// 生成器内部使用的变量契约模型，保持和输出 JSON 字段一一对应。
    /// </summary>
    private sealed class VariableContract
    {
        /// <summary>
        /// 创建变量契约。
        /// </summary>
        public VariableContract(string key, string name, string description, string clrType, string tsType)
        {
            Key = key;
            Name = name;
            Description = description;
            ClrType = clrType;
            TsType = tsType;
        }

        /// <summary>
        /// 前后端统一变量 key，例如 toolkit.message。
        /// </summary>
        public string Key { get; }

        /// <summary>
        /// 前端生成代码中的变量成员名。
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// 来自后端 XML 文档的变量说明。
        /// </summary>
        public string Description { get; }

        /// <summary>
        /// 后端完整 CLR 类型名，供后续诊断或更完整生成使用。
        /// </summary>
        public string ClrType { get; }

        /// <summary>
        /// 当前阶段生成到 TypeScript 的类型表达式。
        /// </summary>
        public string TsType { get; }
    }

    /// <summary>
    /// 生成器内部使用的方法契约模型，保持和输出 JSON 字段一一对应。
    /// </summary>
    private sealed class MethodContract
    {
        /// <summary>
        /// 创建方法契约。
        /// </summary>
        public MethodContract(
            string key,
            string name,
            string description,
            IReadOnlyList<ParameterContract> parameters,
            string returnDescription,
            string returnType)
        {
            Key = key;
            Name = name;
            Description = description;
            Parameters = parameters;
            ReturnDescription = returnDescription;
            ReturnType = returnType;
        }

        /// <summary>
        /// 前后端统一方法 key，例如 toolkit.echo。
        /// </summary>
        public string Key { get; }

        /// <summary>
        /// 前端生成代码中的方法成员名。
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// 来自后端 XML 文档的方法说明。
        /// </summary>
        public string Description { get; }

        /// <summary>
        /// 方法参数契约列表，按后端声明顺序输出。
        /// </summary>
        public IReadOnlyList<ParameterContract> Parameters { get; }

        /// <summary>
        /// 来自后端 XML 文档的返回值说明。
        /// </summary>
        public string ReturnDescription { get; }

        /// <summary>
        /// 当前阶段生成到 TypeScript 的返回类型表达式。
        /// </summary>
        public string ReturnType { get; }
    }

    /// <summary>
    /// 生成器内部使用的方法参数契约模型。
    /// </summary>
    private sealed class ParameterContract
    {
        /// <summary>
        /// 创建方法参数契约。
        /// </summary>
        public ParameterContract(string name, string description, string tsType)
        {
            Name = name;
            Description = description;
            TsType = tsType;
        }

        /// <summary>
        /// 后端参数名，也是生成 TypeScript 代理时的参数名。
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// 来自后端 XML 文档的参数说明。
        /// </summary>
        public string Description { get; }

        /// <summary>
        /// 当前阶段生成到 TypeScript 的参数类型表达式。
        /// </summary>
        public string TsType { get; }
    }
}
